# Nome da Aplicação
spring.application.name=Atividade-em-grupo

# Configuração correta do MySQL na porta 3306 apontando para o banco AttrRh
spring.datasource.url=jdbc:mysql://localhost:3306/AttrRh?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Definição da porta do servidor Backend
server.port=8080