# URL de conexão com o MySQL (Cria o banco AttrRh caso ele não exista)
spring.datasource.url=jdbc:mysql://localhost:3306/AttrRh?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC

# Login do seu banco de dados local
spring.datasource.username=root

# SUBSTITUA pela senha que você configurou no seu MySQL Workbench
spring.datasource.password=

# Driver de Conexão oficial
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações do Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

# Faz com que o Spring crie/atualize as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update